projects:
  recipes:
    schemaPath: amplify/backend/api/recipes/build/schema.graphql
    includes:
      - ./graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ./api/models.ts
        docsFilePath: ./graphql
        region: us-east-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
